<?php

namespace Orizaba\LaravelComponents\Providers;


use Illuminate\Support\ServiceProvider;


class LaravelComponents extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }


    public function boot()
    {

    }
}